spring:
  application:
    name: gateway-server
  profiles:
    active: default
  redis:
    host: 192.168.16.129
    port: 6379
    database: 0

server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: service-user
        uri: lb://SERVICE-USER
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=1
      - id: service-order
        uri: lb://SERVICE-ORDER
        predicates:
        - Path=/api/order/**
        filters:
        - StripPrefix=1
  profiles: default

---

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: service-user
        uri: lb://SERVICE-USER
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
      - id: service-order
        uri: lb://SERVICE-ORDER
        predicates:
        - Path=/api/order/**
        filters:
        - StripPrefix=1
  profiles: host_route
